### ISSUE TITLE
Endless loop on brute force

### ISSUE THREAD

**Issue by hackituria** [Paradoxis/StegCracker#1]
Hi,

When I tried a brute force with this script with a dictionary, like rockyou, the brute force never ended. When the script finishes reading the dictionary, it starts reading it again.

Thx.

**Comment by Paradoxis** [comment]
Hey,

Could you provide me with the image (or similar one that doesn’t work) and a wordlist so I can reproduce it?

Thanks!

**Comment by hackituria** [comment]
I tried with rockyou.txt dictionary and the brute force never finished.

**Comment by Paradoxis** [comment]
@hackituria are you sure it's not just that rockyou.txt is *absolutely huge*, I haven't ever managed to run through the entire thing myself but using a shortened version works fine for me.

**Comment by Paradoxis** [comment]
Closed due to inactivity
