### ISSUE TITLE
Percentage goes beyond 100%

### ISSUE THREAD

**Issue by jraber** [Paradoxis/StegCracker#11]
# What went wrong?
The percentage started at 0.00%, slowly increased to 100.00%, then continued increasing.  Its at >231% now, and still increasing.

## To Reproduce
Run 'stegcracker afile.jpg rockyou.txt' where afile.jpg is normal jpg image that has not been processed using steghide

### StegCracker Version
stegcracker==2.0.6

### StegCracker Type
/home/auser/.local/bin/stegcracker: Python script, ASCII text executable

### StegHide Version
steghide version 0.5.1

### Python Version
Python 3.7.3

**Comment by Paradoxis** [comment]
Thanks for the report! I'll look into it later today :)

**Comment by Paradoxis** [comment]
Spotted and fixed. The `amount` variable in the thread loop was not set to 0 between each chunk iteration, leading to an exponential guess attempts increase. Also spotted an issue where super long passwords would conflict with shorter passwords on certain terminals. See commit db62186 for more info
