### ISSUE TITLE
Unhandled exception in cracker thread

### ISSUE THREAD

**Issue by RymkusDev** [Paradoxis/StegCracker#13]
# What went wrong?
I try to brute force an image jpg with stegcracker. I try to you use this worlist `/usr/share/wordlists/rockyou.txt.gz`. When i launch the command `Stegcrack <image> Path <wordlist>` i get this error :

## Stack Trace
If you got a stack trace, please paste it here:

```
Error: Unhandled exception in cracker thread. Please report this issue on the official bug tracker: "https://github.com/Paradoxis/StegCracker/issues" and don't forget to include the following traceback:
ValueError: embedded null byte
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/stegcracker/cracker.py", line 92, in crack
    with Popen([
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
Error: Terminating due to previous exception..
```

## To Reproduce
Please add the following files / info:

- The file you wish to crack (or one which can reproduce the issue)
- The password file you're using (unless it's rockyou, I have that already)
- The password you know the file is encrypted with

## System information
Please add the output of the following commands:

### StegCracker Version
```
$  pip3 freeze | grep stegcracker
...
```

### StegCracker Type
```
$ file $(which stegcracker)
...
```

### StegHide Version
```
$ steghide --version
...
```

### Python Version
```
$ python3 --version
...
```

### System Version
```
$ uname -a
...

$ cat /etc/issue
...
```

## Screenshots
A picture tells a thousand words, feel free to add one here if you have it

## Other stuff
Got any other info I should know about? Have a monkeypatch or proposed fix?  <br>
Feel like ranting about something? Feel free to do it here. Compliments are also welcome ✨

**Comment by Paradoxis** [comment]
@RymkusDev could you please fill in the template provided, I can’t help without proper debug information so I can reproduce the issue

**Comment by Paradoxis** [comment]
Fixed issue template for you, it also appears you're using the gzipped version of the wordlist, and not the actual text file. You'll have to unzip it as such before use:

```
$ gzip -d /usr/share/wordlists/rockyou.txt.gz
```

**Comment by RymkusDev** [comment]
Thx a lot Paradoxis !
