### ISSUE TITLE
bash: stegcracker: command not found

### ISSUE THREAD

**Issue by mrhili** [Paradoxis/StegCracker#16]
i installed steghide and your repo with pip3

i run it and didn't work

i tested with sudo but none results

my machine is : #1 SMP Debian 5.7.17-1kali1 (2020-08-26)

The bin directory
$ ls /usr/local/bin/
asm       common     cyclic  disablenx  elfdiff   errno  main  pwn       ROPgadget  shellcraft  unhex
checksec  constgrep  debug   disasm     elfpatch  hex    phd   pwnstrip  scramble   template    update

**Comment by mrhili** [comment]
$ ls /bin | grep steg
steghide
stegosuite

**Comment by mrhili** [comment]
osboxes@osboxes:~/Desktop/Chalenges/picoCTF2018/stego$ python3 --version
Python 3.8.5
osboxes@osboxes:~/Desktop/Chalenges/picoCTF2018/stego$ python3.5 --version
bash: python3.5: command not found
osboxes@osboxes:~/Desktop/Chalenges/picoCTF2018/stego$ python3.6 --version
bash: python3.6: command not found
osboxes@osboxes:~/Desktop/Chalenges/picoCTF2018/stego$ python3.7 --version
bash: python3.7: command not found
osboxes@osboxes:~/Desktop/Chalenges/picoCTF2018/stego$

**Comment by mrhili** [comment]
PS C:\Users\HP> npm install -g vue
+ vue@2.6.12
added 1 package from 1 contributor in 33.477s

**Comment by Paradoxis** [comment]
>PS C:\Users\HP> npm install -g vue
>  * vue@2.6.12
>    added 1 package from 1 contributor in 33.477s

Your last command indicates you're using Windows, and possibly with a combination of WSL or Git Bash which all aren't officially supported. Furthermore, you didn't fill out any of the issue template so I can't help debug the issue for you. Please fill them out in the future as it's near impossible to help you debug the issue.

If anything it seems like stegcracker just hasn't been added to your path, check your Python's site-packages bin directory or run it with:

```
$ python3 -m stegcracker ...
```
