### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by sicinthemind** [Paradoxis/StegCracker#3]
Stegcracker will execute and give false-positive checking on a file that doesn't exist.

**Comment by sicinthemind** [comment]
Recommended Add line 13+

    if [ ! -f $1 ]; then
       echo -e "\e[31mError:\e[0m File '$1' does not exist!"
       exit 1
    fi

**Comment by Paradoxis** [comment]
Added in commit e2a5059, thanks for the help :)
