### ISSUE TITLE
Stegcracker Not Finding Known Password

### ISSUE THREAD

**Issue by ghost** [Paradoxis/StegCracker#4]
Hi,

I'm doing a hackthebox challenge and using stegcracker for some steg CTFs.  Unfortunately it doesn't seem to be working for me, when I run it against an image I know the passphrase for (and put that in my list) it never gets it, I just get:

```

$ sudo /bin/stegcracker first.jpg guesses.txt
StegCracker - (https://github.com/Paradoxis/StegCracker)
Copyright (c) 2018 - Luke Paris (Paradoxis)

Attacking file 'first.jpg' with wordlist 'guesses.txt'..
\x1B[31mError:\x1B[0m Failed to crack file, ran out of passwords.
```

I've attached the files I'm using

![first](https://user-images.githubusercontent.com/5190790/42994247-76f21fb0-8c05-11e8-94b4-db75833afb32.jpg)
[guesses.txt](https://github.com/Paradoxis/StegCracker/files/2213258/guesses.txt)

**Comment by Paradoxis** [comment]
Thanks for the bug report, I'll try to look at it this weekend :)

**Comment by Paradoxis** [comment]
@papafett Could you tell me which password it should be exactly? Makes it a bit easier to debug

**Comment by Paradoxis** [comment]
Might be related to the fact `guesses.txt` doesn't end with a newline, as the [read](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/read.html) specs state:

> The read utility shall read a single line from standard input.
> 
> By default, unless the -r option is specified, <backslash> shall act as an escape character. An unescaped <backslash> shall preserve the literal value of the following character, with the exception of a <newline>. If a <newline> follows the <backslash>, the read utility shall interpret this as line continuation. The <backslash> and <newline> shall be removed before splitting the input into fields. All other unescaped <backslash> characters shall be removed after splitting the input into fields.
> 
> If standard input is a terminal device and the invoking shell is interactive, read shall prompt for a continuation line when it reads an input line ending with a <backslash> <newline>, unless the -r option is specified.
> 
> The terminating <newline> (if any) shall be removed from the input and the results shall be split into fields as in the shell for the results of parameter expansion (see Field Splitting); [...]

Changing line 73 to the following might fix your problem:

```bash
done < <(grep "" $wordlist)

**Comment by Paradoxis** [comment]
Tested & fixed

**Comment by wallofsheep** [comment]
Did the following with the same issue noted above:

Updated to the latest:
pip3 install stegcracker -U --force-reinstall

steghide embed -cf image.jpg -ef secret.txt
created a password of "password" and several other words in it for testing.

created a file named dict.txt with the word "password" in it.
ran:
stegcracker image.jpg dict.txt
Error: Failed to crack file, ran out of passwords.

Tried downloading tom.txt and using a password from that file with a image.jpg and I get the same error.

**Comment by Paradoxis** [comment]
Did you remove the previous installation of stegcracker? You can test this
by running: cat $(which stegcracker) it should return the contents of a
Python script

If the output is the latest verison, try running it with the --verbose
option
