### ISSUE TITLE
Writting to the console on every loop is horribly inefficient

### ISSUE THREAD

**Issue by pluggles** [Paradoxis/StegCracker#6]
Hello,

Writing to the command line for every loop really slows down a program like this, especially when using large dictionaries like rockyou.txt

I would recommend only writing the percent completed of the word list, and only writing that when ever the value changes, 

and perhaps have an argument/flag to output attempt for debugging.

**Comment by Paradoxis** [comment]
Hey, thanks for the feedback! You're absolutely right, it's why I've been considering re-writing the whole thing in Python and even adding multithreading to it.

I initially just wrote it as a useful tool for myself to use in CTF's as ended up becoming more popular than expected. I'm currently quite busy so I don't have the time to do this yet, but if you're up for adding that flag for now I'm happy to accept a pull request that comes my way :)

**Comment by Paradoxis** [comment]
Small update: I've started working on a full rewrite, can't say exactly when it will be done but it's on it's way :)

**Comment by Paradoxis** [comment]
Good news: I've just released the Python rewrite, new features include:

- Multithreading
- Quiet and Verbose options
- CI / CD
- A **huge** performance increase compared to the previous version (~2960% increase) 

See the README for further details, if you run into any issues, please let me know! :)
